import PropTypes from 'prop-types';
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import '../globals.css';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='m-1'>
        {children}
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};

export default RootLayout;
